// _angular_backup/src/app/projects/projects.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { faCode, faExternalLinkAlt } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.css']
})
export class ProjectsComponent implements OnInit {
  codeIcon = faCode;
  extLinkIcon = faExternalLinkAlt;
  @Input() darkTheme: boolean = true;
  
  constructor() { }

  ngOnInit(): void {
  }

}
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@500&display=swap" rel="stylesheet">
<body [ngClass]="darkTheme ? 'body-dark' : 'body-light'">
    <div id="project" style="height: 60px; background-color: transparent;"></div>
    <section class="project">
        <h2 class="section-title">Projects</h2>
        <div class="project-container">
            <img src="assets/Tic-Tac-Toe.jpg" alt="Tic-Tac-Toe" height="250" width="450" />
            <div class="project-content">
                <h3>Tic Tac Toe</h3>
                    <p>The last page of every student's notebook is reserved for Tic Tac Toe. Let's revisit those cherished childhood memories and ride the waves of nostalgia. </p>
                <div class="project-skill">
                    <span>Python</span>
                    <span>ML</span>
                    <span>Maths</span>
                    <span>Tkinter</span>
                </div>
                <div class="project-link">
                    <span>
                        <a href="https://github.com/sumagnadey/Mini_Project/tree/master/Tic%20Tac%20Toe" aria-label="Source code" title="source code" target="_blank" rel="noopener">
                            <fa-icon [icon]="codeIcon" class="icon-border fas fa-code"></fa-icon>
                        </a>
                    </span>
                    <!-- <span>
                        <a href="#" aria-label="Preview" title="preview" rel="noopener">
                            <fa-icon [icon]="extLinkIcon" aria-hidden="true" class="icon-border fas fa-external-link-alt"></fa-icon>
                        </a>
                    </span> -->
                </div>
            </div>
        </div>
    
        <div class="project-container">
            <img src="https://blog.dormakaba.com/tachyon/2020/04/dormakaba-Blog-Post-pictures-_-1024-x-683-83.jpg" alt="Face Recognition" height="250" width="450" />
            <div class="project-content">
                <h3>Face Recognition </h3>
                <p>Developed an authentication system based on Face Recognition.</p>
                <div class="project-skill">
                    <span>Python </span>
                    <span>Digital Image Processing</span>
                    <span>Open CV</span>
                </div>
                <div class="project-link">
                    <span>
                        <a href="https://github.com/sumagnadey/Mini_Project/tree/master/Face_recognition" aria-label="Source code" target="_blank"
                            title="source code" rel="noopener">
                            <fa-icon [icon]="codeIcon" class="icon-border fas fa-code"></fa-icon>
                        </a>
                    </span>
                    <!-- <span>
                        <a href="#" aria-label="Preview" target="_blank" title="preview" rel="noopener">
                            <fa-icon [icon]="extLinkIcon" aria-hidden="true" class="icon-border fas fa-external-link-alt"></fa-icon>
                        </a>
                    </span> -->
                </div>
            </div>
        </div>

        <div class="project-container">
            <img src="https://www.researchgate.net/publication/340884113/figure/fig3/AS:883691647684610@1587699915907/Structure-and-operation-of-InfoGAN-Information-maximizing-Generative-Adversarial.png" alt="image-2022-07-26-201920536" height="250" width="450" />
            <div class="project-content">
                <h3>Generate Faces</h3>
                <p>Generate new images of faces using Generative Adversarial Networks (GAN)</p>
                <div class="project-skill">
                    <span>Python</span>
                    <span>Pytorch</span>
                    <span>Deep CNN</span>
                </div>
                <div class="project-link">
                    <span>
                        <a href="https://github.com/sumagnadey/Udacity_Deep_Learning_NanoDegree/tree/master/4.%20project-face-generation" aria-label="Source code" title="source code" target="_blank" rel="noopener">
                            <fa-icon [icon]="codeIcon" class="icon-border fas fa-code"></fa-icon>
                        </a>
                    </span>
                    <!-- <span>
                        <a href="#" aria-label="Preview" title="preview" rel="noopener">
                            <fa-icon [icon]="extLinkIcon" aria-hidden="true" class="icon-border fas fa-external-link-alt"></fa-icon>
                        </a>
                    </span> -->
                </div>
            </div>
        </div>

        <div class="project-container">
            <img src="assets/Covid19.png" height="250" width="450" />
            <div class="project-content">
                <h3>Detecting COVID-19 using Deep Learning</h3>
                <p>Developed an CNN model to predict whether subject has Covid-19 or not.</p>
                <div class="project-skill">
                    <span>Python</span>
                    <span>PyTorch</span>
                    <span>TensorFlow</span>
                    <span>Pillow</span>
                </div>
                <div class="project-link">
                    <span>
                        <a href="https://github.com/sumagnadey/Mini_Project/tree/master/covid%20detection" aria-label="Source code" title="source code" target="_blank" rel="noopener">
                            <fa-icon [icon]="codeIcon" class="icon-border fas fa-code"></fa-icon>
                        </a>
                    </span>
                    <!-- <span>
                        <a href="#" aria-label="Preview" title="preview" rel="noopener">
                            <fa-icon [icon]="extLinkIcon" aria-hidden="true" class="icon-border fas fa-external-link-alt"></fa-icon>
                        </a>
                    </span> -->
                </div>
            </div>
        </div>
    </section>
</body>

// src/components/Projects.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { Github, ExternalLink } from 'lucide-react';
import './Projects.css';

const projects = [
    {
        title: "Tic Tac Toe",
        description: "The last page of every student's notebook is reserved for Tic Tac Toe. Let's revisit those cherished childhood memories and ride the waves of nostalgia.",
        image: "/assets/Tic-Tac-Toe.jpg",
        tags: ["Python", "ML", "Maths", "Tkinter"],
        githubUrl: "https://github.com/sumagnadey/Mini_Project/tree/master/Tic%20Tac%20Toe",
        liveUrl: null
    },
    {
        title: "Face Recognition",
        description: "Developed an authentication system based on Face Recognition.",
        image: "/assets/face_recognition.png",
        tags: ["Python", "Digital Image Processing", "Open CV"],
        githubUrl: "https://github.com/sumagnadey/Mini_Project/tree/master/Face_recognition",
        liveUrl: null
    },
    {
        title: "Generate Faces",
        description: "Generate new images of faces using Generative Adversarial Networks (GAN)",
        image: "https://www.researchgate.net/publication/340884113/figure/fig3/AS:883691647684610@1587699915907/Structure-and-operation-of-InfoGAN-Information-maximizing-Generative-Adversarial.png",
        tags: ["Python", "Pytorch", "Deep CNN"],
        githubUrl: "https://github.com/sumagnadey/Udacity_Deep_Learning_NanoDegree/tree/master/4.%20project-face-generation",
        liveUrl: null
    },
    {
        title: "Detecting COVID-19 using Deep Learning",
        description: "Developed an CNN model to predict whether subject has Covid-19 or not.",
        image: "/assets/Covid19.png",
        tags: ["Python", "PyTorch", "TensorFlow", "Pillow"],
        githubUrl: "https://github.com/sumagnadey/Mini_Project/tree/master/covid%20detection",
        liveUrl: null
    }
];

const Projects = () => {
    return (
        <section id="projects" className="section projects-section">
            <div className="container">
                <div className="section-header text-center">
                    <h2 className="section-title">Featured <span className="text-gradient">Projects</span></h2>
                    <p className="section-subtitle">Some of the selected works I've built</p>
                </div>

                <div className="projects-grid">
                    {projects.map((project, index) => (
                        <motion.div
                            key={index}
                            className="project-card glass-card"
                            initial={{ opacity: 0, scale: 0.9 }}
                            whileInView={{ opacity: 1, scale: 1 }}
                            viewport={{ once: true, amount: 0.1 }}
                            transition={{ duration: 0.5, delay: index * 0.1 }}
                            whileHover={{ y: -10 }}
                        >
                            <div className="project-image-wrapper">
                                <img src={project.image} alt={project.title} className="project-image" loading="lazy" />
                                <div className="project-overlay">
                                    <div className="project-links">
                                        {project.githubUrl && (
                                            <a href={project.githubUrl} target="_blank" rel="noreferrer" className="project-link-icon" aria-label="GitHub Repository">
                                                <Github size={24} />
                                            </a>
                                        )}
                                        {project.liveUrl && (
                                            <a href={project.liveUrl} target="_blank" rel="noreferrer" className="project-link-icon" aria-label="Live Demo">
                                                <ExternalLink size={24} />
                                            </a>
                                        )}
                                    </div>
                                </div>
                            </div>

                            <div className="project-content">
                                <h3 className="project-title">{project.title}</h3>
                                <p className="project-desc">{project.description}</p>

                                <div className="project-tags">
                                    {project.tags.map((tag, i) => (
                                        <span key={i} className="project-tag">{tag}</span>
                                    ))}
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default Projects;
