// _angular_backup/src/app/app.component.ts
import { isPlatformBrowser } from '@angular/common';
import { AfterViewInit, Component, HostListener, Inject, PLATFORM_ID, Renderer2 } from '@angular/core';
import { faHackerrank, faInstagram } from '@fortawesome/free-brands-svg-icons';
import { faBolt, faChevronUp, faCloudBolt, faCloudRain, faCloudShowersHeavy, faCloudShowersWater, faCloudSun, faDroplet, faIcicles, faLocationDot, faRainbow, faSmog, faSnowflake, faSun, faTemperatureArrowDown, faTemperatureThreeQuarters } from '@fortawesome/free-solid-svg-icons';
import { HttpClient } from '@angular/common/http';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit{
	title = 'portfolio';
	scrollIcon = faChevronUp;
	hackerrankIcon = faHackerrank;
	instagramIcon =  faInstagram;
	locationIcon = faLocationDot;
	temperatureIcon = faTemperatureThreeQuarters;

	darkTheme = false;

	time: any;
	hours: any;
	msg: any;
	location: any;
	urlString: any;
	temperature: any;
	latitude: any;
	longitude: any;
	wcode: any;
	weather: any;
	weatherIcon: any;


	

	weathercode = [
		{
			code: [0],
			desc: 'Clear Sky',
			icon: faSun
		},
		{
			code: [1, 2, 3],
			// desc: 'Mainly clear, partly cloudy, and overcast',
			desc: 'Cloudy',
			icon: faCloudSun
		},
		{
			code: [45, 48],
			// desc: 'Fog and depositing rime fog',
			desc: 'Fog',
			icon: faSmog
		},
		{
			code: [51, 53, 55],
			// desc: 'Drizzle: Light, moderate, and dense intensity',
			desc: 'Drizzle',
			icon: faRainbow
		},
		{
			code: [56, 57],
			// desc: 'Freezing Drizzle: Light and dense intensity',
			desc: 'Freezing Drizzle',
			icon: faDroplet
		},
		{
			code: [61, 63, 65],
			// desc: 'Rain: Slight, moderate and heavy intensity',
			desc: 'Rain',
			icon: faCloudRain
		},
		{
			code: [66, 67],
			// desc: 'Freezing Rain: Light and heavy intensity',
			desc: 'Freezing Rain',
			icon: faCloudShowersHeavy
		},
		{
			code: [71, 73, 75],
			// desc: 'Snow fall: Slight, moderate, and heavy intensity',
			desc: 'Snowfall',
			icon: faTemperatureArrowDown
		},
		{
			code: [77],
			desc: 'Snow Grains',
			icon: faIcicles
		},
		{
			code: [80, 81, 82],
			// desc: 'Rain showers: Slight, moderate, and violent',
			desc: 'Rain Showers',
			icon: faCloudShowersWater
		},
		{
			code: [85, 86],
			// desc: 'Snow showers slight and heavy',
			desc: 'Snow Showers',
			icon: faSnowflake
		},
		{
			code: [95],
			// desc: 'Thunderstorm: Slight or moderate',
			desc: 'Thunderstorm',
			icon: faBolt
		},
		{
			code: [96, 99],
			// desc: 'Thunderstorm with slight and heavy hail',
			desc: 'Thunderstorm with Hail',
			icon: faCloudBolt
		},
	];

	images = [
		{
			imageSrc: 'assets/IITInternship.jpg',
			imageAlt: ''
		},
		{
			imageSrc: 'assets/GoogleCloud.png',
			imageAlt: ''
		},
		{
			imageSrc: 'assets/AzureFundamental.jpg',
			imageAlt: ''
		},
		{
			imageSrc: 'assets/Bengalathon.jpg',
			imageAlt: ''
		},
		{
			imageSrc: 'assets/Udacity.jpg',
			imageAlt: ''
		},
		{
			imageSrc: 'assets/AIForMed.jpeg',
			imageAlt: ''
		},
		{
			imageSrc: 'assets/MLStanford.jpeg',
			imageAlt: ''
		},
	];
	constructor(@Inject(PLATFORM_ID) private platformId: Object, private renderer: Renderer2, private http: HttpClient) {
		setInterval(() => {
			this.time = new Date();
		}, 1000);

		this.decide();
	}

	ngAfterViewInit(): void {
		if (isPlatformBrowser(this.platformId)) {
			let loader = this.renderer.selectRootElement('#loader');
			if (loader.style.display != "none") loader.style.display = "none";
		}
	}

	ngOnInit(): void {
		this.getData();
	}

	getWeatherDescription() {
		for(let temp of this.weathercode)
		{
			// console.log(temp);
			if(temp.code.includes(this.wcode)) {
				this.weatherIcon = temp.icon;
				this.weather = temp.desc;
			}
		}
	}

	async getData() {
		const res = await fetch('https://ipwho.is/');
		const json = await res.json();
		this.latitude = json.latitude;
		this.longitude = json.longitude;
		this.location = json.region + ", " + json.country;

		this.urlString = "https://api.open-meteo.com/v1/forecast?latitude=" + this.latitude + "&longitude=" + this.longitude + "&current_weather=true&timezone=auto";

		const res2 = await fetch(this.urlString);
		const json2 = await res2.json();
		this.temperature = json2.current_weather.temperature;
		this.wcode = json2.current_weather.weathercode;
		this.getWeatherDescription();
	}

	decide() {
		this.hours = new Date().getHours();
		if(this.hours < 5){
			this.msg = "Hello !";
			this.darkTheme = true;
		}
		else if(this.hours < 12){
			this.msg = " Hi, Good Morning !";
			this.darkTheme = false;
		}
		else if(this.hours == 12){
			this.msg = "Hi, Good Noon !";
			this.darkTheme = false;
		}
		else if(this.hours < 16){
			this.msg = "Hi, Good Afternoon !";
			this.darkTheme = false;
		}
		else if(this.hours < 18){
			this.msg = "Hi, Good Evening !";
			this.darkTheme = false;
		}
		else if(this.hours < 21){
			this.msg = "Hi, Good Evening !";
			this.darkTheme = true;
		}
		else if(this.hours < 24){
			this.msg = "Bonjour !";
			this.darkTheme = true;
		}
	}

	toggleTheme(theme: boolean) {
		this.darkTheme = theme;
	}

	isShow: boolean | undefined;
	topPosToStartShowing = 300;
  
	@HostListener('window:scroll')
	checkScroll() {

	  const scrollPosition = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0;
  
	//   console.log('[scroll]', scrollPosition);
	  
	  if (scrollPosition >= this.topPosToStartShowing) {
		this.isShow = true;
	  } else {
		this.isShow = false;
	  }
	}

	gotoTop() {
	  window.scroll({ 
		top: 0, 
		left: 0, 
		behavior: 'smooth' 
	  });
	}
}
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=0.5">
	</head>
	<body class="mainBody" [ngClass]="darkTheme ? 'body-dark' : 'body-light'">
		<link rel="preconnect" href="https://fonts.gstatic.com" />
		<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.14.0/devicon.min.css"/>
		<script src="https://kit.fontawesome.com/fa62c117c7.js" crossorigin="anonymous"></script>
		<div class="container-fluid">
			<app-navbar [darkTheme]="darkTheme" (newItemEvent)="toggleTheme($event)"></app-navbar>
			<app-intro [darkTheme]="darkTheme" [msg]="msg" [temperature]="temperature" [weather]="weather" [weatherIcon]="weatherIcon"></app-intro>
			<app-experience [darkTheme]="darkTheme"></app-experience>
			<app-education [darkTheme]="darkTheme"></app-education>
			<app-skillset [darkTheme]="darkTheme"></app-skillset>
			<app-projects [darkTheme]="darkTheme"></app-projects>
			<app-research [darkTheme]="darkTheme"></app-research>
			<app-certification [darkTheme]="darkTheme"></app-certification>
			<app-contacts [darkTheme]="darkTheme"></app-contacts>
			<app-time [darkTheme]="darkTheme" [time]="time" [location]="location"></app-time>
			<!-- <app-edu-update></app-edu-update> -->
			<footer>
				<div class="footer_div">
					<button>
						<a href="https://leetcode.com/Sumagna007/" target="_blank">
							<img src="https://upload.wikimedia.org/wikipedia/commons/1/19/LeetCode_logo_black.png">
						</a>
					</button>
					<button>
						<a href="https://www.hackerrank.com/sumagna_dey/" target="_blank">
							<img src="https://img.icons8.com/external-tal-revivo-shadow-tal-revivo/24/null/external-hackerrank-is-a-technology-company-that-focuses-on-competitive-programming-logo-shadow-tal-revivo.png">
						</a>
					</button>
					<button>
						<a href="https://scholar.google.com/citations?user=iFBk_AIAAAAJ&hl=en" target="_blank">
							<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Google_Scholar_logo.svg/2048px-Google_Scholar_logo.svg.png">
						</a>
					</button>
					<button>
						<a href="https://www.researchgate.net/profile/Sumagna-Dey" target="_blank">
							<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/ResearchGate_icon_SVG.svg/1200px-ResearchGate_icon_SVG.svg.png">
						</a>
					</button>
					<button>
						<a href="https://orcid.org/0000-0001-5739-722X" target="_blank">
							<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/ORCID_iD.svg/2048px-ORCID_iD.svg.png">
						</a>
					</button>
				</div>
			</footer>
	
			<div class="scroll-container">
				<div aria-label="Scroll up" class="scroll-up">
					<a *ngIf="isShow" (click)="gotoTop()">
						<fa-icon [icon]="scrollIcon" aria-hidden="true" class="fas fa-arrow-up"></fa-icon>
					</a>
				</div>
			</div>
		</div>
	</body>
</html>

// src/App.jsx
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronUp, MapPin, Clock } from 'lucide-react';
import Navbar from './components/Navbar';
import ParallaxBackground from './components/ParallaxBackground';
import Hero from './components/Hero';
import Experience from './components/Experience';
import Education from './components/Education';
import Skillset from './components/Skillset';
import Projects from './components/Projects';
import Research from './components/Research';
import Certifications from './components/Certifications';
import Contact from './components/Contact';
import './App.css';

function App() {
  const [darkTheme, setDarkTheme] = useState(false);
  const [showScrollTop, setShowScrollTop] = useState(false);
  const [currentTime, setCurrentTime] = useState(new Date());
  const [location, setLocation] = useState('Hyderabad, India');
  const [weatherCondition, setWeatherCondition] = useState('clear');

  // Initialize theme based on local time (from Angular)
  useEffect(() => {
    const hours = new Date().getHours();
    if (hours < 5 || hours >= 18) {
      setDarkTheme(true);
    } else {
      setDarkTheme(false);
    }
  }, []);

  // Apply dark mode class to body
  useEffect(() => {
    if (darkTheme) {
      document.body.classList.add('dark-mode');
    } else {
      document.body.classList.remove('dark-mode');
    }
  }, [darkTheme]);

  // Live clock (from Angular time component)
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  // Fetch weather for Hyderabad
  useEffect(() => {
    const fetchWeather = async () => {
      try {
        const res = await fetch('https://api.open-meteo.com/v1/forecast?latitude=17.3850&longitude=78.4867&current_weather=true&timezone=auto');
        const data = await res.json();
        const code = data.current_weather.weathercode;

        let condition = 'clear';
        if ([1, 2, 3, 45, 48].includes(code)) condition = 'cloudy';
        else if ([51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 80, 81, 82].includes(code)) condition = 'rain';
        else if ([71, 73, 75, 77, 85, 86].includes(code)) condition = 'snow';
        else if ([95, 96, 99].includes(code)) condition = 'thunderstorm';

        setWeatherCondition(condition);
      } catch (e) {
        console.error("Weather fetch failed:", e);
      }
    };
    fetchWeather();
  }, []);

  // Scroll to top visibility
  useEffect(() => {
    const handleScroll = () => {
      setShowScrollTop(window.scrollY > 300);
    };
    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const toggleTheme = () => {
    setDarkTheme((prev) => !prev);
  };

  const scrollToTop = () => {
    window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
  };

  const formatTime = (date) => {
    return date.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true
    });
  };

  const formatDate = (date) => {
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  // Footer social links (from Angular) — using reliable icon sources
  const footerLinks = [
    { name: 'LeetCode', url: 'https://leetcode.com/Sumagna007/', icon: 'https://cdn.iconscout.com/icon/free/png-256/free-leetcode-3521542-2944960.png' },
    { name: 'HackerRank', url: 'https://www.hackerrank.com/sumagna_dey/', icon: 'https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/160_Hackerrank_logo_logos-512.png' },
    { name: 'Google Scholar', url: 'https://scholar.google.com/citations?user=iFBk_AIAAAAJ&hl=en', icon: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Google_Scholar_logo.svg' },
    { name: 'ResearchGate', url: 'https://www.researchgate.net/profile/Sumagna-Dey', icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/ResearchGate_icon_SVG.svg/1280px-ResearchGate_icon_SVG.svg.png' },
    { name: 'ORCID', url: 'https://orcid.org/0000-0001-5739-722X', icon: 'https://upload.wikimedia.org/wikipedia/commons/0/06/ORCID_iD.svg' }
  ];

  return (
    <div className="app-container">
      <ParallaxBackground darkTheme={darkTheme} weatherCondition={weatherCondition} />
      <Navbar darkTheme={darkTheme} toggleTheme={toggleTheme} />

      <main>
        <Hero darkTheme={darkTheme} weatherCondition={weatherCondition} />
        <Experience darkTheme={darkTheme} />
        <Education darkTheme={darkTheme} />
        <Skillset darkTheme={darkTheme} />
        <Projects darkTheme={darkTheme} />
        <Research darkTheme={darkTheme} />
        <Certifications darkTheme={darkTheme} />
        <Contact darkTheme={darkTheme} />
      </main>

      {/* Live Time & Location Widget */}
      <div className="time-widget">
        <Clock size={16} />
        <span>{formatTime(currentTime)}</span>
        <span className="time-separator" />
        <span>{formatDate(currentTime)}</span>
        {location && (
          <>
            <span className="time-separator" />
            <MapPin size={14} />
            <span>{location}</span>
          </>
        )}
      </div>

      {/* Footer with Social Links */}
      <footer className="app-footer">
        <div className="container">
          <div className="footer-social-links">
            {footerLinks.map((link) => (
              <a
                key={link.name}
                href={link.url}
                target="_blank"
                rel="noreferrer"
                className="footer-social-link"
                title={link.name}
              >
                {link.icon ? (
                  <img src={link.icon} alt={link.name} />
                ) : (
                  <span className="footer-emoji">{link.emoji}</span>
                )}
              </a>
            ))}
          </div>
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="footer-powered"
          >
            Crafted with ❤️ Sumagna
          </motion.div>
        </div>
      </footer>

      {/* Scroll to Top Button */}
      <AnimatePresence>
        {showScrollTop && (
          <motion.button
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.5 }}
            transition={{ duration: 0.3 }}
            className="scroll-to-top"
            onClick={scrollToTop}
            aria-label="Scroll to top"
          >
            <ChevronUp size={22} />
          </motion.button>
        )}
      </AnimatePresence>
    </div>
  );
}

export default App;
