// src/components/Education.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { GraduationCap, Award, MapPin, Calendar, Building2 } from 'lucide-react';
import './Education.css';

const educationData = [
    {
        degree: "B.Tech (CSE)",
        school: "Meghnad Saha Institute of Technology",
        university: "MAKAUT",
        score: "DGPA: 8.84",
        location: "Kolkata, India",
        date: "2017 - 2021",
        frontImage: "/assets/College.jpg",
        backLogo: "/assets/msit_logo.jpg",
        accent: '#818cf8',
    },
    {
        degree: "Higher Secondary",
        school: "Kenduadihi High School",
        university: "WBCHSE",
        score: "Percentage: 89%",
        location: "Bankura, India",
        date: "2015 - 2017",
        frontImage: "/assets/Kenduadihi.jpg",
        backLogo: "https://upload.wikimedia.org/wikipedia/en/b/b7/West_Bengal_Council_of_Higher_Secondary_Education_Logo.png",
        accent: '#a78bfa',
    },
    {
        degree: "Secondary",
        school: "Kenduadihi High School",
        university: "WBBSE",
        score: "Percentage: 91.14%",
        location: "Bankura, India",
        date: "2012 - 2015",
        frontImage: "https://content.jdmagicbox.com/comp/kenduadihi/w2/9999p3242.3242.181113152752.v2w2/catalogue/kenduadihi-high-school-kenduadihi-schools-30ja00m02y.jpg?clr=423824",
        backLogo: "https://upload.wikimedia.org/wikipedia/en/d/d9/West_Bengal_Board_of_Secondary_Education_Logo.png",
        accent: '#c084fc',
    }
];

const Education = () => {
    return (
        <section id="education" className="section education-section">
            <div className="container">
                <div className="section-header text-center">
                    <h2 className="section-title">My <span className="text-gradient">Education</span></h2>
                    <p className="section-subtitle">Academic background and qualifications</p>
                </div>

                <div className="edu-cards-row">
                    {educationData.map((edu, index) => (
                        <motion.div
                            key={index}
                            className="edu-card-v2"
                            initial={{ opacity: 0, y: 40 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true, amount: 0.2 }}
                            transition={{ duration: 0.5, delay: index * 0.15 }}
                            whileHover={{ y: -8 }}
                        >
                            {/* Hero image area */}
                            <div className="edu-v2-image">
                                <img src={edu.frontImage} alt={edu.school} />
                                <div className="edu-v2-image-overlay" />
                                <div className="edu-v2-degree-badge">{edu.degree}</div>
                                <div className="edu-v2-logo">
                                    <img src={edu.backLogo} alt={edu.university} />
                                </div>
                            </div>

                            {/* Card body */}
                            <div className="edu-v2-body">
                                <h3 className="edu-v2-school">{edu.school}</h3>
                                <span className="edu-v2-university">{edu.university}</span>

                                <div className="edu-v2-meta">
                                    <div className="edu-v2-meta-item">
                                        <Calendar size={13} />
                                        <span>{edu.date}</span>
                                    </div>
                                    <div className="edu-v2-meta-item">
                                        <MapPin size={13} />
                                        <span>{edu.location}</span>
                                    </div>
                                </div>

                                <div className="edu-v2-score" style={{ '--accent': edu.accent }}>
                                    <Award size={16} />
                                    <strong>{edu.score}</strong>
                                </div>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default Education;

// _angular_backup/src/app/education/education.component.ts
import { Component, Input } from '@angular/core';
import { faBookOpenReader, faBuildingColumns, faGraduationCap, faLocationDot, faSchool, faTimeline, faUpRightFromSquare } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-education',
  templateUrl: './education.component.html',
  styleUrls: ['./education.component.css']
})
export class EducationComponent {
  @Input() darkTheme: boolean = true;
  locationIcon = faLocationDot;
  timelineIcon = faTimeline;
  graduationIcon = faGraduationCap;
  academyIcon = faBuildingColumns;
  schoolIcon = faSchool;
  scoreIcon = faBookOpenReader
  linkIcon = faUpRightFromSquare
}

<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">

<body [ngClass]="darkTheme ? 'body-dark' : 'body-light'">
  <div id="education" style="height: 7px; background-color: transparent;"></div>
  <section class="stack">
    <h2 class="section-title">Education</h2>
    <div class="card-list">
      <div class="flip-card" tabIndex="0">
        <div class="flip-card-inner">
          <div class="flip-card-front">
            <img src="assets/College.jpg">

            <div class="card_title title-white">
              <p><fa-icon [icon]="graduationIcon"></fa-icon> B.Tech (CSE)</p>
          </div>

          </div>
          <div class="flip-card-back">
            <div class="flip-back-test">
              <img src="https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Maulana_Abul_Kalam_Azad_University_of_Technology_Logo.svg/800px-Maulana_Abul_Kalam_Azad_University_of_Technology_Logo.svg.png" height="70">
              <p><fa-icon [icon]="schoolIcon"></fa-icon> 
                Meghnad Saha Institute of Technology
                <br>
                <fa-icon [icon]="academyIcon"></fa-icon> MAKAUT
                <br>
                <fa-icon [icon]="scoreIcon"></fa-icon> DGPA: 8.84
                <br>
                <fa-icon [icon]="locationIcon"></fa-icon> Kolkata, India
                <br>
                <fa-icon [icon]="timelineIcon"></fa-icon> 2017 - 2021
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="flip-card" tabIndex="0">
        <div class="flip-card-inner">
          <div class="flip-card-front">
            <img src="assets/Kenduadihi.jpg">

            <div class="card_title title-white">
              <p><fa-icon [icon]="graduationIcon"></fa-icon> Higher Secondary</p>
          </div>
          </div>
          <div class="flip-card-back">
            <div class="flip-back-test">
              <img src="https://upload.wikimedia.org/wikipedia/en/b/b7/West_Bengal_Council_of_Higher_Secondary_Education_Logo.png" height="70">
              <p>
                <fa-icon [icon]="schoolIcon"></fa-icon>  Kenduadihi High School
                <br>
                <fa-icon [icon]="academyIcon"></fa-icon> WBCHSE
                <br>
                <fa-icon [icon]="scoreIcon"></fa-icon> Percentage: 89%
                <br>
                <fa-icon [icon]="locationIcon"></fa-icon> Bankura, India
                <br>
                <fa-icon [icon]="timelineIcon"></fa-icon> 2015 - 2017
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="flip-card" tabIndex="0">
        <div class="flip-card-inner">
          <div class="flip-card-front">
            <img src="https://content.jdmagicbox.com/comp/kenduadihi/w2/9999p3242.3242.181113152752.v2w2/catalogue/kenduadihi-high-school-kenduadihi-schools-30ja00m02y.jpg?clr=423824">

            <div class="card_title title-white">
              <p><fa-icon [icon]="graduationIcon"></fa-icon> Secondary</p>
          </div>

          </div>
          <div class="flip-card-back">
            <div class="flip-back-test">
              <img src="https://upload.wikimedia.org/wikipedia/en/d/d9/West_Bengal_Board_of_Secondary_Education_Logo.png" height="70">
              <p><fa-icon [icon]="schoolIcon"></fa-icon>  
                Kenduadihi High School
                <br>
                <fa-icon [icon]="academyIcon"></fa-icon> WBBSE
                <br>
                <fa-icon [icon]="scoreIcon"></fa-icon> Percentage: 91.14%
                <br>
                <fa-icon [icon]="locationIcon"></fa-icon> Bankura, India
                <br>
                <fa-icon [icon]="timelineIcon"></fa-icon> 2012 - 2015
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>
